### ISSUE TITLE
FYI: when beeing installed, doesn't make vendor folder

### ISSUE THREAD

**Issue by japrescott** [imagemin/mozjpeg-bin#13]
after installation, I got the error;
node_modules/mozjpeg-stream/node_modules/mozjpeg/vendor/cjpeg ENOENT

I had to manually call the install.js file
node node_modules/mozjpeg-stream/node_modules/mozjpeg/lib/install.js

after that, mozjpeg can be used.

Thought I'd let the community know..

**Comment by shinnn** [comment]
This is a bin-build issue.

**Comment by throrin19** [comment]
I have the same problem bu I can't launch the `node node_modules/mozjpeg-stream/node_modules/mozjpeg/lib/install.js` because I'm in docker container. Why it does not works ? mozjpeg require a dependance ?
