### ISSUE TITLE
installation fails on OS X

### ISSUE THREAD

**Issue by thisconnect** [imagemin/mozjpeg-bin#16]
OS X 10.11.5
Xcode Version 7.3.1
Node v6.2.0 

```
npm i mozjpeg-bin
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> mozjpeg-bin@0.2.1 postinstall /Users/me/project/node_modules/mozjpeg-bin
> node postinstall.js

Building mozjpeg...
(node:2942) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
✗ Error: Command failed: autoreconf -fiv && ./configure --prefix="/Users/me/project/node_modules/mozjpeg-bin/bin" --bindir="/Users/me/project/node_modules/mozjpeg-bin/bin" --libdir="/Users/me/project/node_modules/mozjpeg-bin/bin" && make install
/bin/sh: autoreconf: command not found
```

**Comment by thisconnect** [comment]
apparently this is fixed in the next release https://github.com/mozilla/mozjpeg/pull/205

**Comment by pornel** [comment]
`autoreconf: command not found` sounds like you simply don't have autotools installed. If you don't have build dependencies, then in the next major release you'll see `cmake: command not found` instead ;)

**Comment by thisconnect** [comment]
@pornel yes I am a bit lazy and hope there will be binaries :)

**Comment by deamme** [comment]
@thisconnect Libtool is required for the build to work. I used homebrew to get it.

`brew install libtool`

**Comment by thisconnect** [comment]
hi again. https://github.com/mozilla/mozjpeg/pull/205 is merged!! -suitable-emoticon-here-

For imagemin-mozjpeg cosumers: should the installation process of `brew install autoconf` and `brew install libtool` be documented in the installation section of the imagemin-mozjpeg readme?

**Comment by wbobeirne** [comment]
Also throwing out there that #26 can also be a pain point for osx installs.

**Comment by 1000ch** [comment]
Please try [the newest version](https://github.com/imagemin/mozjpeg-bin/releases/tag/v7.0.0), it passed the tests for macOS.
