### ISSUE TITLE
Mozjpeg 3.2 is out

### ISSUE THREAD

**Issue by albertogasparin** [imagemin/mozjpeg-bin#25]
It includes :
- updated libjpeg-turbo (v1.5.0)
- Fixed interaction of JINT_DC_SCAN_OPT_MODE and JBOOLEAN_OPTIMIZE_SCANS
- #define JPEG_C_PARAM_SUPPORTED 1 for easier interoperability with stock libjpeg
- Minor bugfixes in yuvjpeg/jpegyuv test helper tools

Moreover it could be a nice opportunity to fix OSX installation failure.
Thanks

**Comment by Krato** [comment]
What about this?
