### ISSUE TITLE
Support for  `Internal Network`

### ISSUE THREAD

**Issue by doxiaodong** [imagemin/mozjpeg-bin#28]
Some people cannot download sources by public network.
So the next url cannot be reached `https://github.com/mozilla/mozjpeg/releases/download/v3.1/mozjpeg-3.1-release-source.tar.gz`.

Please put it in npm source or make it configurable in ENV such as `export IMAGEMIN_MOZJPEG_SOURCE=https://github.com/mozilla/mozjpeg/releases/download/v3.1/mozjpeg-3.1-release-source.tar.gz`

The same problem with `pngquant-bin`, `gifsicle-bin`, `optipng-bin`, ...

Please!

**Comment by shinnn** [comment]
It should be fixed in one of mozjpeg-bin dependencies.

**Comment by doxiaodong** [comment]
Any plan?

**Comment by doxiaodong** [comment]
How about this?
