### ISSUE TITLE
npm install error 7.1.1

### ISSUE THREAD

**Issue by efrenpastor** [imagemin/mozjpeg-bin#67]
```sh
[node  4/21] RUN npm install
npm notice 
npm notice New major version of npm available! 7.4.3 -> 8.0.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.0.0>
npm notice Run `npm install -g npm@8.0.0` to update!``
npm notice 
npm ERR! code 1
npm ERR! path /src/node_modules/mozjpeg
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! compiling from source
npm ERR! Command failed: /src/node_modules/mozjpeg/vendor/cjpeg -version
npm ERR! /src/node_modules/mozjpeg/vendor/cjpeg: /lib/x86_64-linux-gnu/libz.so.1: version 'ZLIB_1.2.9' not found 
(required by /src/node_modules/mozjpeg/vendor/cjpeg)
npm ERR! 
npm ERR! 
**npm ERR! mozjpeg pre-build test failed**
npm ERR! Error: Command failed: /bin/sh -c ./configure --enable-static --disable-shared --disable-dependency-
tracking --with-jpeg8  --prefix="/src/node_modules/mozjpeg/vendor" --bindir="/src/node_modules/mozjpeg/vendor" --libdir="/src/node_modules/mozjpeg/vendor"
npm ERR! configure: error: no nasm (Netwide Assembler) found
```

Since your last change in the test file in version 7.1.1 our Build process has stopped working.
We have fixed it by locking the version to the previous one.

I am commenting this in case anyone else has this problem until it is fixed.

**Comment by neo** [comment]
just solved a similar issue:

if you're using docker or "stretch" debian (which is the [default docker tagged version](https://hub.docker.com/_/node) for `node:14` and below), consider using "bullseye" or "buster" instead as it has a newer version of `zlib` (1.2.11 v.s. 1.2.8): https://packages.debian.org/bullseye/zlib1g

**Comment by richard-balakrishnan** [comment]
i am facing similar issue, 

mozjpeg@7.1.1 postinstall D:\Richard\react-samples\node_modules\mozjpeg
 node lib/install.js

Hostname/IP does not match certificate's altnames: Host: raw.githubusercontent.com. is not in the cert's altnames: DNS:api.demo.dns.simplifyd.app
mozjpeg pre-build test failed
compiling from source
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -fiv"
'autoreconf' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tolixian** [comment]
I am facing the similar issue,
#16 186.6 > mozjpeg@7.1.1 postinstall /workspace/node_modules/mozjpeg
#16 186.6 > node lib/install.js
#16 186.6 
#16 187.3 Command failed: /workspace/node_modules/mozjpeg/vendor/cjpeg -version
#16 187.3 /workspace/node_modules/mozjpeg/vendor/cjpeg: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /workspace/node_modules/mozjpeg/vendor/cjpeg)
#16 187.3 
#16 187.3 
#16 187.3 mozjpeg pre-build test failed

**Comment by 1000ch** [comment]
For the version 7.1.1, please make sure to install this package after https://github.com/imagemin/mozjpeg-bin/issues/67#issuecomment-950043912.

**Comment by tommym9** [comment]
> Please make sure that your environment has `nasm`, `zlib`, and `automake` if macOS.
> 
> ```shell
> # for macOS
> brew install automake nasm zlib
> 
> # for Ubuntu
> sudo apt-get install nasm zlib1g-dev
> ```

This isn't working for me using docker (via DDEV). Installing the `nasm` and `zlib1g-dev` packages hasn't changed the error message either.

Happy to provide any debug info over, but npm isn't my forte so not sure whats going to be helpful here.

Cheers

Tom

**Comment by Sun-FreePort** [comment]
> > Please make sure that your environment has `nasm`, `zlib`, and `automake` if macOS.
> > ```shell
> > # for macOS
> > brew install automake nasm zlib
> > 
> > # for Ubuntu
> > sudo apt-get install nasm zlib1g-dev
> > ```
> 
> This isn't working for me using docker (via DDEV). Installing the `nasm` and `zlib1g-dev` packages hasn't changed the error message either.
> 
> Happy to provide any debug info over, but npm isn't my forte so not sure whats going to be helpful here.
> 
> Cheers
> 
> Tom

Hi Tom, can you share your Dockerfile? (desensitization)

I think we can include package in Dockerfile, because the step will effect `npm build`, when I tested.
