### ISSUE TITLE
mozjpeg v3.1 is out.

### ISSUE THREAD

**Issue by shinnn** [imagemin/mozjpeg-bin#9]
https://github.com/mozilla/mozjpeg/releases/tag/v3.1

**Comment by kevva** [comment]
For some reason I can't compile this on my Ubuntu system.

**Comment by serhatdurum** [comment]
:+1:

**Comment by olizilla** [comment]
Can we get a `mozjpeg-bin` release with that version bump in please?

**Comment by shinnn** [comment]
Fixed in v4.1.2 https://github.com/imagemin/mozjpeg-bin/releases/tag/v4.1.2.
